name: ascii-myworkflow
on: push
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout action
          uses: actions/checkout@v6
        - name: Exccute shell scritpy first
          run: ./myscripy.sh  
       